### ISSUE TITLE
icudt62.dll in 32bit package is 64bits

### ISSUE THREAD

**Issue by JJRousseau** [AnimMouse/QTFiles#2]
I was getting 193 errors with the 32bit package until I checked out the icudt62.dll and discovered it's actually 64bit. I grabbed the 32bit version from the previous release and it now works fine.

**Comment by AnimMouse** [comment]
Oops, I accidentally used a dummy icudt62.dll for 64 bit on 32 bit package.
Thanks for pointing it out, haven't tried to use 32 bit qaac until now.

**Comment by AnimMouse** [comment]
Fixed on 6109d035a239c6e78ed21486203832e04308cc05 by generating the dummy icudt62.dll during the releasing process.
